copy_raw_html:
  type: bool
  default: false
  description: "If selected the copied contents will be raw HTML instead of the stripped down plain text"
min_trust_level:
  type: integer
  default: 5
  max: 5
  description: "Select the minimum trust level required to see the widget. (Select 5 to show to all users)"
