copy_type:
  type: enum
  default: markdown
  choices:
    - markdown
    - html
  description: "Select the type of copied text you would like saved to the clipboard."
copy_button_allowed_groups:
  type: list
  list_type: group
  default: "11" # trust_level_1
  description: "Select the groups that are allowed to use the copy button."
